version: "3.9"
services:
  api:
    build: 
      context: ./
      dockerfile: ./api/Dockerfile

    # volumes:
    #   - ./api:/expressjs
    ports:
      - 5000:5000
    depends_on:
      - db
  
  db:
    image: mariadb
    restart: always
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: zelye

  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      PMA_PORT: 3306
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: zelye
    ports:
      - 8080:80
    depends_on: 
      - db

  # frontend:
  #   build: ./client/
  #   env_file: ./client/.env
  #   ports:
  #     - "3000:3000"
  #   command: yarn start
