name: deploy-main
on: 
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy zelye qr menu
        uses: actions/checkout@v3

        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}

      - run: docker compose down 
      - run: docker compose up --build