INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (0,'﻿Goveja juha','image-0.jpeg','Okusna goveja juha z zelenjavo in rezinami govejega mesa',0,3.5,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (1,'Korenčkova juha','image-1.jpeg','Sveža in osvežilna juha iz korenja z začimbami',0,4.0,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (2,'Paradižnikova juha','image-2.jpeg','Topla juha iz svežih paradižnikov z začimbami',0,3.75,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (3,'Lečina juha','image-3.jpeg','Okusna juha iz leče z zelenjavo in začimbami',0,3.5,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (4,'Cvetačna juha','image-4.jpeg','Sveža juha iz cvetače z začimbami in kremastim mlekom',0,3.2,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (5,'Milk shake','image-5.jpeg','Mlečni napitek',1,3.5,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (6,'Frape','image-6.jpeg','Borovnica, gozdni sadeži, banana',1,4.2,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (7,'Gosti sok s smetano ','image-7.jpeg','Gosti sok s smetano ',1,2.8,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (8,'Bananin napitek','image-8.jpeg','naravni pomarančni sok, banana, med ',1,3.4,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (9,'Limonada','image-9.jpeg','Naravno iztisnjena limonada',1,2.1,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (10,'Coca cola','image-10.jpeg','3dl',2,2.2,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (11,'Fanta','image-11.jpeg','3dl',2,2.2,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (12,'Sprite','image-12.jpeg','3dl',2,2.2,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (13,'Bitter Lemon','image-13.jpeg','3dl',2,2.2,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (14,'Orangina','image-14.jpeg','3dl',2,2.3,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (15,'Tonic','image-15.jpeg','3dl',2,2.2,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (16,'Cockta','image-16.jpeg','3dl',2,2.2,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (17,'Sok v steklenički','image-17.jpeg','jagoda, pomaranča, breskev - 3 dl',2,2.2,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (18,'Radenska','image-18.jpeg','3dl',2,1.6,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (19,'Oaza','image-19.jpeg','5dl',2,1.6,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (20,'Negazirana voda','image-20.jpeg','5dl',2,1.8,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (21,'Ledeni čaj','image-21.jpeg','1dl',2,0.9,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (22,'Red Bull','image-22.jpeg','0,33l',2,3.5,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (23,'Točeno pivo','image-23.jpeg','0,5l',3,2.4,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (24,'Union','image-24.jpeg','0,5l',3,3.1,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (25,'Zlatorog','image-25.jpeg','0,5l',3,2.8,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (26,'Heineken','image-26.jpeg','0,5l',3,3.3,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (27,'Radler','image-27.jpeg','0,5l',3,2.8,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (28,'Brezalkoholno pivo','image-28.jpeg','0,5l',3,3.5,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (29,'Somersby','image-29.jpeg','0,5l',4,3.1,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (30,'Jabolčni TAT','image-30.jpeg','0,33l',4,2.8,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (31,'Jack Daniels','image-31.jpeg','0,03l',5,3.5,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (32,'Johnnie Walker red label','image-32.jpeg','0,03l',5,3.5,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (33,'Jameson','image-33.jpeg','0,33l',5,3.5,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (34,'Domači rum','image-34.jpeg','0,03l',5,3.5,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (35,'Gin Beefeater','image-35.jpeg','0,03l',5,3.5,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (36,'Grappa','image-36.jpeg','0,33l',5,3.5,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (37,'Stock','image-37.jpeg','0,03l',5,3.5,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (38,'Sadjevec','image-38.jpeg','0,03l',5,3.5,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (39,'Travarica','image-39.jpeg','0,33l',5,2.8,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (40,'Belo vino','image-40.jpeg','0,1l',6,1.4,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (41,'Rdeče vino','image-41.jpeg','0,1l',6,1.4,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (42,'Srebrna penina','image-42.jpeg','0,1l',6,1.6,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (43,'Zlata penina','image-43.jpeg','0,1l',6,1.6,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (44,'Prima classica','image-44.jpeg','Pica obložena z šunko, sirom in gobami',7,7.6,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (45,'Prima cremissima','image-45.jpeg','Pica obložena s šunko, sirom in gobovo kremo',7,7.9,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (46,'Prima fresca','image-46.jpeg','Pica obložena s sirom, panceto, rukolo, svežo papriko in šampinjoni',7,8.3,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (47,'Prima giavola','image-47.jpeg','Pica obložena s sirom, salamo, feferoni, papriko in šampinjoni',7,8.6,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (48,'Prima mexicana','image-48.jpeg','Pica obložena z mletim mesom, nacho sirom, rdečim fižolem, papriko in koruzo',7,8.6,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (49,'Con Salame','image-49.jpeg','Pica obložena s sirom, šunko, kuhanim pršutom, suho salamo in gobami',7,8.8,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (50,'Con Prosciutto','image-50.jpeg','Pica obložena s sirom, pršutom in gobami',7,8.6,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (51,'Caprese','image-51.jpeg','Pica obložena z rukolo, sirom, mozzarello in paradižnikom',7,7.6,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (52,'Margherita','image-52.jpeg','Pica obložena s sirom in olivo',7,6.1,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (53,'Con Tonno','image-53.jpeg','Pica obložena s sirom, tuno, tržasko omako in paradižnikom',8,8.2,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (54,'Frutti di mare','image-54.jpeg','Pica obložena s sirom, gamberi, dagnji, lignji in tržasko omako',8,10.6,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (55,'Prima triesta','image-55.jpeg','Pica obložena s sirom, panceto, vratovino, pečeno papriko in tržaško omako',9,8.8,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (56,'Prima speciale','image-56.jpeg','Pica obložena s sirom, umešanim jajčko, mozzarello, budjolo in rukolo',9,10.9,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (57,'Margherita','image-57.jpeg','Napoletana pica obložena s šunko, sirom in gobovo kremo',10,7.6,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (58,'Calabrese','image-58.jpeg','Napoletana pica obložena s šunko, sirom in gobovo kremo',10,11.3,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (59,'Budjola al pistacchio','image-59.jpeg','Napoletana pica obložena s šunko, sirom in gobovo kremo',10,9.8,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (60,'Vegetariano','image-60.jpeg','Napoletana pica obložena s šunko, sirom in gobovo kremo',10,8.8,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (61,'Napoletana','image-61.jpeg','Napoletana pica obložena s šunko, sirom in gobovo kremo',10,9.3,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (62,'Capricciosa','image-62.jpeg','Napoletana pica obložena s šunko, sirom in gobovo kremo',10,9.2,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (63,'Zelenjava','image-63.jpeg','pelati, paradižnik, paprika, melancani, artičoke, beluši, koruza, feferoni, rukola',11,1.2,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (64,'Salame','image-64.jpeg','šunka, kuhan pršut, vratovina, suha salama, hrenovka, pršut, budjola, panceta',11,2.2,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (65,'Siri','image-65.jpeg','trdi sir, mozzarella, beli sir, nacho sir, grana padano',11,2.2,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (66,'Gobe','image-66.jpeg','šampinjoni, jurčki',11,1.4,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (67,'Morski sadeži','image-67.jpeg','mešani morski sadeži, škampi, inčuni',11,2.2,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (68,'Omake in prelivi','image-68.jpeg','jurčkova omaka, tržaška omaka, tatarska omaka, kisla smetana,',11,2.0,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (69,'Jajce','image-69.jpeg','',11,0.8,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (70,'Gratinirane palačinke s skuto','image-70.jpeg','Palačinke s skuto zapečene v krušni peči',12,4.6,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (71,'Palačinke','image-71.jpeg','Palačinke s čokolado, marmelado, lešniki ali orehi',12,4.1,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (72,'Brownie','image-72.jpeg','Topli čokoladni biskvit, sladoled, lešniki',12,5.2,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (73,'Banana split','image-73.jpeg','',12,5.2,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (74,'Sladoled kepica','image-74.jpeg','Izberite si okus pri sladoledni vitrini',12,1.5,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (75,'Svedri z gamberi in pinjolami','image-75.jpeg','Gamberi, pesto, pinjole, češnjev paradižnik, ricotta, paradižnikova omaka, grana padano…',13,11.2,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (76,'Rezanci z morskimi sadeži','image-76.jpeg','gamberi, dagnje, lignji, česen, vino, paradižnikova omaka',13,11.2,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (77,'Tris testenin','image-77.jpeg','Široki rezanci s smetano in pršutom, tortelini s sirom z modro plesnijo, njoki s štirimi zelišči',13,9.4,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (78,'Toskanski tris','image-78.jpeg','Svedri s pomarančo, poprom in piščancem, rižota z jurčki in dimljenim sirom, široki rezanci s smetano in pršutom…',13,9.6,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (79,'Tris klasika','image-79.jpeg','Špageti po bolonjsko, njoki carbonara, mesna lazanja…',13,9.4,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (80,'Lazanja z bolonjsko omako','image-80.jpeg','Testnina, mleto meso s paradižnikovo omako, bešamel, grana padano, kisla smetana, sir…',13,8.1,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (81,'Njoki s 4 siri','image-81.jpeg','Njoki s sirom z modro plesnijo, ementalcem, dimljenim sirom, in grana padanom, zapečni v krušni peči',13,9.6,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (82,'Tortelini s sirom','image-82.jpeg','Tortelini s sirom z modro plesnijo, bučkami, korenjem in smetano, zapčeni v krušni peči',13,10.9,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (83,'Classic burger','image-83.jpeg','Ketchup, majoneza, govedina, zelena solata, čebula, paradižnik',14,7.6,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (84,'Cheeseburger','image-84.jpeg','Ketchup, majoneza, govedina, zelena solata, čebula, paradižnik, sir',14,7.8,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (85,'Chickenburger','image-85.jpeg','Ketchup, majoneza, piščančja prsa, zelena solata, čebula, paradižnik',14,7.5,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (86,'Mexico burger','image-86.jpeg','Koktejl omaka, omaka chili pop, goveje meso, jalapeno paprika, paradižnik, kumare',14,7.9,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (87,'Puranji zrezek po dunajsko','image-87.jpeg','S prilogo: ocvrt krompirčk, tatarska omaka',15,8.6,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (88,'Ocvrt piščančji file','image-88.jpeg','Polnjen s šunko in sirom, priložen pomfrit in tatarska omaka',15,8.9,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (89,'Puranji zrezek s sirom, smetano in gobami','image-89.jpeg','Priloga: krompirjevi kroketi',15,9.1,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (90,'Ocvrti lignji','image-90.jpeg','Priloga: ocvrt krompirčk, tatarska omaka',15,11.2,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (91,'Ocvrt sir','image-91.jpeg','Priloga: ocvrt krompirčk, tatarska omaka',15,7.9,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (92,'Rižota s piščancem in gobami','image-92.jpeg','Piščančji file, gobe, smetana…',16,8.6,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (93,'Paella','image-93.jpeg','Piščančji file, gamberi, paradižnik, smetana, rukola, češnjev paradižnik, grana padano..',16,11.5,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (94,'Rižota z zelenjavo','image-94.jpeg','Paprika, bučke, por, paradižnik, smetana, rukola, češnjev paradižnik, grana padano…',16,6.9,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (95,'Rižota z roastbeefom','image-95.jpeg','Roastbeef, sušeni paradižniki, paradižnikova omaka, rukala, češnjev paradižnik, grana padano…',16,12.2,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (96,'Tunina solata','image-96.jpeg','Zelena solata, radič, rukola, tuna, koromač, koruza, tatarska omaka',17,7.2,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (97,'Mixta','image-97.jpeg','Zelena solata, radič, koruza, rukola, ribani beli sir, olive, hišni preliv…',17,6.9,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (98,'Solata z mozzarello','image-98.jpeg','Zelena solata, radič, koruza, rukola, mozzarella, olive, hišni preliv…',17,6.9,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (99,'Ocvrta solata','image-99.jpeg','Zelena solata, rukola, radič, ocvrte bučke, paprika in melancani, ocvrt sir, tatarska omaka…',17,9.2,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (100,'Piščančja solata','image-100.jpeg','Piščanec v smetanovi omaki, zelena solata, radič, rukola, jajčevci, sojina omaka, balzamični kis…',17,8.1,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (101,'Cezarjeva solata','image-101.jpeg','Zelena solata, radič, piščanec, kruhovke kocke, jajce, rukola, koruza, balzamični preliv…',17,7.9,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (102,'Pomrit','image-102.jpeg','',18,3.5,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (103,'Takitosi','image-103.jpeg','Ocvrti zavitki iz tortilij polnjene s piščancem',18,7.2,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (104,'Zelenjavni takitosi','image-104.jpeg','Ocvrti zavitki iz tortilij polnjene z zelenjavo',18,7.0,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (105,'Hrenovke v listnatem testu','image-105.jpeg','Hrenavke zavite v listanto testo in polite z jajcem',18,5.6,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (106,'Kava','image-106.jpeg','',19,1.3,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (107,'Macchiato','image-107.jpeg','',19,1.6,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (108,'Kava s smetano','image-108.jpeg','',19,1.6,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (109,'Bela kava','image-109.jpeg','',19,1.9,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (110,'Brezkofeinska kava','image-110.jpeg','',19,1.6,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (111,'Irska kava','image-111.jpeg','',20,4.3,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (112,'Ledena kava','image-112.jpeg','',20,3.9,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (113,'Čaj','image-113.jpeg','',21,1.4,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (114,'Vroča čokolada','image-114.jpeg','',21,2.2,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (115,'Kakav','image-115.jpeg','',21,1.7,'EUR');
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (116,'Mleko','image-116.jpeg','',21,1.0,'EUR');
