INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (1,"﻿Goveja juha","default.jpeg","Okusna goveja juha z zelenjavo in rezinami govejega mesa",1,3.5,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (2,"Korenčkova juha","86134_Carrotsoup.png","Sveža in osvežilna juha iz korenja z začimbami",1,4.0,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (3,"Paradižnikova juha","229783_Tomatosoup.png","Topla juha iz svežih paradižnikov z začimbami",1,3.75,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (4,"Lečina juha","235779_Lentilsoup.png","Okusna juha iz leče z zelenjavo in začimbami",1,3.5,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (5,"Cvetačna juha","307726_Cauliflowersoup.png","Sveža juha iz cvetače z začimbami in kremastim mlekom",1,3.2,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (6,"Milk shake","default.jpeg","Mlečni napitek",2,3.5,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (7,"Frape","default.jpeg","Borovnica, gozdni sadeži, banana",2,4.2,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (8,"Gosti sok s smetano ","default.jpeg","Gosti sok s smetano ",2,2.8,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (9,"Bananin napitek","default.jpeg","naravni pomarančni sok, banana, med ",2,3.4,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (10,"Limonada","default.jpeg","Naravno iztisnjena limonada",2,2.1,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (11,"Coca cola","default.jpeg","3dl",3,2.2,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (12,"Fanta","default.jpeg","3dl",3,2.2,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (13,"Sprite","default.jpeg","3dl",3,2.2,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (14,"Bitter Lemon","default.jpeg","3dl",3,2.2,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (15,"Orangina","default.jpeg","3dl",3,2.3,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (16,"Tonic","default.jpeg","3dl",3,2.2,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (17,"Cockta","default.jpeg","3dl",3,2.2,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (18,"Sok v steklenički","default.jpeg","jagoda, pomaranča, breskev - 3 dl",3,2.2,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (19,"Radenska","default.jpeg","3dl",3,1.6,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (20,"Oaza","default.jpeg","5dl",3,1.6,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (21,"Negazirana voda","default.jpeg","5dl",3,1.8,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (22,"Ledeni čaj","default.jpeg","1dl",3,0.9,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (23,"Red Bull","default.jpeg","0,33l",3,3.5,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (24,"Točeno pivo","default.jpeg","0,5l",4,2.4,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (25,"Union","default.jpeg","0,5l",4,3.1,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (26,"Zlatorog","default.jpeg","0,5l",4,2.8,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (27,"Heineken","default.jpeg","0,5l",4,3.3,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (28,"Radler","default.jpeg","0,5l",4,2.8,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (29,"Brezalkoholno pivo","default.jpeg","0,5l",4,3.5,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (30,"Somersby","default.jpeg","0,5l",5,3.1,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (31,"Jabolčni TAT","default.jpeg","0,33l",5,2.8,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (32,"Jack Daniels","default.jpeg","0,03l",6,3.5,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (33,"Johnnie Walker red label","default.jpeg","0,03l",6,3.5,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (34,"Jameson","default.jpeg","0,33l",6,3.5,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (35,"Domači rum","default.jpeg","0,03l",6,3.5,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (36,"Gin Beefeater","default.jpeg","0,03l",6,3.5,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (37,"Grappa","default.jpeg","0,33l",6,3.5,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (38,"Stock","default.jpeg","0,03l",6,3.5,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (39,"Sadjevec","default.jpeg","0,03l",6,3.5,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (40,"Travarica","default.jpeg","0,33l",6,2.8,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (41,"Belo vino","default.jpeg","0,1l",7,1.4,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (42,"Rdeče vino","default.jpeg","0,1l",7,1.4,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (43,"Srebrna penina","default.jpeg","0,1l",7,1.6,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (44,"Zlata penina","default.jpeg","0,1l",7,1.6,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (45,"Prima classica","493773_Pizza.png","Pica obložena z šunko, sirom in gobami",8,7.6,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (46,"Prima cremissima","343862_Pizzamargherita.png","Pica obložena s šunko, sirom in gobovo kremo",8,7.9,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (47,"Prima fresca","413157_Pizza.png","Pica obložena s sirom, panceto, rukolo, svežo papriko in šampinjoni",8,8.3,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (48,"Prima giavola","default.jpeg","Pica obložena s sirom, salamo, feferoni, papriko in šampinjoni",8,8.6,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (49,"Prima mexicana","401787_Pizza.png","Pica obložena z mletim mesom, nacho sirom, rdečim fižolem, papriko in koruzo",8,8.6,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (50,"Con Salame","315359_Pizzamargherita.png","Pica obložena s sirom, šunko, kuhanim pršutom, suho salamo in gobami",8,8.8,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (51,"Con Prosciutto","594941_Pizza.png","Pica obložena s sirom, pršutom in gobami",8,8.6,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (52,"Caprese","default.jpeg","Pica obložena z rukolo, sirom, mozzarello in paradižnikom",8,7.6,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (53,"Margherita","default.jpeg","Pica obložena s sirom in olivo",8,6.1,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (54,"Con Tonno","default.jpeg","Pica obložena s sirom, tuno, tržasko omako in paradižnikom",9,8.2,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (55,"Frutti di mare","default.jpeg","Pica obložena s sirom, gamberi, dagnji, lignji in tržasko omako",9,10.6,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (56,"Prima triesta","default.jpeg","Pica obložena s sirom, panceto, vratovino, pečeno papriko in tržaško omako",10,8.8,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (57,"Prima speciale","default.jpeg","Pica obložena s sirom, umešanim jajčko, mozzarello, budjolo in rukolo",10,10.9,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (58,"Margherita","default.jpeg","Napoletana pica obložena s šunko, sirom in gobovo kremo",11,7.6,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (59,"Calabrese","default.jpeg","Napoletana pica obložena s šunko, sirom in gobovo kremo",11,11.3,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (60,"Budjola al pistacchio","default.jpeg","Napoletana pica obložena s šunko, sirom in gobovo kremo",11,9.8,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (61,"Vegetariano","default.jpeg","Napoletana pica obložena s šunko, sirom in gobovo kremo",11,8.8,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (62,"Napoletana","default.jpeg","Napoletana pica obložena s šunko, sirom in gobovo kremo",11,9.3,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (63,"Capricciosa","default.jpeg","Napoletana pica obložena s šunko, sirom in gobovo kremo",11,9.2,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (64,"Zelenjava","default.jpeg","pelati, paradižnik, paprika, melancani, artičoke, beluši, koruza, feferoni, rukola",12,1.2,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (65,"Salame","default.jpeg","šunka, kuhan pršut, vratovina, suha salama, hrenovka, pršut, budjola, panceta",12,2.2,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (66,"Siri","default.jpeg","trdi sir, mozzarella, beli sir, nacho sir, grana padano",12,2.2,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (67,"Gobe","default.jpeg","šampinjoni, jurčki",12,1.4,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (68,"Morski sadeži","default.jpeg","mešani morski sadeži, škampi, inčuni",12,2.2,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (69,"Omake in prelivi","default.jpeg","jurčkova omaka, tržaška omaka, tatarska omaka, kisla smetana,",12,2.0,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (70,"Jajce","default.jpeg","",12,0.8,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (71,"Gratinirane palačinke s skuto","default.jpeg","Palačinke s skuto zapečene v krušni peči",13,4.6,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (72,"Palačinke","112079_Pancakeswithchocolatesauce.png","Palačinke s čokolado, marmelado, lešniki ali orehi",13,4.1,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (73,"Brownie","371806_Brownie.png","Topli čokoladni biskvit, sladoled, lešniki",13,5.2,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (74,"Banana split","494334_Bananasplit.png","",13,5.2,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (75,"Sladoled kepica","324444_Bananaspliticecream.png","Izberite si okus pri sladoledni vitrini",13,1.5,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (76,"Svedri z gamberi in pinjolami","default.jpeg","Gamberi, pesto, pinjole, češnjev paradižnik, ricotta, paradižnikova omaka, grana padano…",14,11.2,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (77,"Rezanci z morskimi sadeži","default.jpeg","gamberi, dagnje, lignji, česen, vino, paradižnikova omaka",14,11.2,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (78,"Tris testenin","default.jpeg","Široki rezanci s smetano in pršutom, tortelini s sirom z modro plesnijo, njoki s štirimi zelišči",14,9.4,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (79,"Toskanski tris","default.jpeg","Svedri s pomarančo, poprom in piščancem, rižota z jurčki in dimljenim sirom, široki rezanci s smetano in pršutom…",14,9.6,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (80,"Tris klasika","default.jpeg","Špageti po bolonjsko, njoki carbonara, mesna lazanja…",14,9.4,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (81,"Lazanja z bolonjsko omako","default.jpeg","Testnina, mleto meso s paradižnikovo omako, bešamel, grana padano, kisla smetana, sir…",14,8.1,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (82,"Njoki s 4 siri","default.jpeg","Njoki s sirom z modro plesnijo, ementalcem, dimljenim sirom, in grana padanom, zapečni v krušni peči",14,9.6,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (83,"Tortelini s sirom","default.jpeg","Tortelini s sirom z modro plesnijo, bučkami, korenjem in smetano, zapčeni v krušni peči",14,10.9,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (84,"Classic burger","118498_Burger.png","Ketchup, majoneza, govedina, zelena solata, čebula, paradižnik",15,7.6,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (85,"Cheeseburger","140216_Cheeseburger.png","Ketchup, majoneza, govedina, zelena solata, čebula, paradižnik, sir",15,7.8,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (86,"Chickenburger","226363_Chickenburger.png","Ketchup, majoneza, piščančja prsa, zelena solata, čebula, paradižnik",15,7.5,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (87,"Mexico burger","125974_Mexicoburger.png","Koktejl omaka, omaka chili pop, goveje meso, jalapeno paprika, paradižnik, kumare",15,7.9,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (88,"Puranji zrezek po dunajsko","32788_Wienerschnitzel.png","S prilogo: ocvrt krompirčk, tatarska omaka",16,8.6,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (89,"Ocvrt piščančji file","302114_Wienerschnitzel.png","Polnjen s šunko in sirom, priložen pomfrit in tatarska omaka",16,8.9,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (90,"Puranji zrezek s sirom, smetano in gobami","113022_Wienerschnitzel.png","Priloga: krompirjevi kroketi",16,9.1,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (91,"Ocvrti lignji","347514_Friedsquid.png","Priloga: ocvrt krompirčk, tatarska omaka",16,11.2,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (92,"Ocvrt sir","571108_Grilledcheese.png","Priloga: ocvrt krompirčk, tatarska omaka",16,7.9,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (93,"Rižota s piščancem in gobami","599170_Risottowithvegetables.png","Piščančji file, gobe, smetana…",17,8.6,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (94,"Paella","default.jpeg","Piščančji file, gamberi, paradižnik, smetana, rukola, češnjev paradižnik, grana padano..",17,11.5,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (95,"Rižota z zelenjavo","353340_Risottowithvegetables.png","Paprika, bučke, por, paradižnik, smetana, rukola, češnjev paradižnik, grana padano…",17,6.9,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (96,"Rižota z roastbeefom","396846_Risottowithvegetables.png","Roastbeef, sušeni paradižniki, paradižnikova omaka, rukala, češnjev paradižnik, grana padano…",17,12.2,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (97,"Tunina solata","60672_Tunasalad.png","Zelena solata, radič, rukola, tuna, koromač, koruza, tatarska omaka",18,7.2,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (98,"Mixta","default.jpeg","Zelena solata, radič, koruza, rukola, ribani beli sir, olive, hišni preliv…",18,6.9,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (99,"Solata z mozzarello","default.jpeg","Zelena solata, radič, koruza, rukola, mozzarella, olive, hišni preliv…",18,6.9,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (100,"Ocvrta solata","default.jpeg","Zelena solata, rukola, radič, ocvrte bučke, paprika in melancani, ocvrt sir, tatarska omaka…",18,9.2,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (101,"Piščančja solata","default.jpeg","Piščanec v smetanovi omaki, zelena solata, radič, rukola, jajčevci, sojina omaka, balzamični kis…",18,8.1,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (102,"Cezarjeva solata","default.jpeg","Zelena solata, radič, piščanec, kruhovke kocke, jajce, rukola, koruza, balzamični preliv…",18,7.9,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (103,"Pomrit","default.jpeg","",19,3.5,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (104,"Takitosi","default.jpeg","Ocvrti zavitki iz tortilij polnjene s piščancem",19,7.2,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (105,"Zelenjavni takitosi","default.jpeg","Ocvrti zavitki iz tortilij polnjene z zelenjavo",19,7.0,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (106,"Hrenovke v listnatem testu","default.jpeg","Hrenavke zavite v listanto testo in polite z jajcem",19,5.6,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (107,"Kava","default.jpeg","",20,1.3,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (108,"Macchiato","default.jpeg","",20,1.6,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (109,"Kava s smetano","default.jpeg","",20,1.6,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (110,"Bela kava","default.jpeg","",20,1.9,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (111,"Brezkofeinska kava","default.jpeg","",20,1.6,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (112,"Irska kava","default.jpeg","",21,4.3,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (113,"Ledena kava","default.jpeg","",21,3.9,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (114,"Čaj","default.jpeg","Različni okusi",22,1.4,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (115,"Vroča čokolada","default.jpeg","",22,2.2,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (116,"Kakav","default.jpeg","",22,1.7,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (117,"Mleko","default.jpeg","",22,1.0,"EUR");
