INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (1,"Goveja juha","image-0.jpeg","Okusna goveja juha z zelenjavo in rezinami govejega mesa",1,3.5,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (2,"Korenčkova juha","image-1.jpeg","Sveža in osvežilna juha iz korenja z začimbami",1,4.0,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (3,"Paradižnikova juha","image-2.jpeg","Topla juha iz svežih paradižnikov z začimbami",1,3.75,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (4,"Lečina juha","image-3.jpeg","Okusna juha iz leče z zelenjavo in začimbami",1,3.5,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (5,"Cvetačna juha","image-4.jpeg","Sveža juha iz cvetače z začimbami in kremastim mlekom",1,3.2,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (6,"Milk shake","image-5.jpeg","Mlečni napitek",2,3.5,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (7,"Frape","image-6.jpeg","Borovnica, gozdni sadeži, banana",2,4.2,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (8,"Gosti sok s smetano ","image-7.jpeg","Gosti sok s smetano ",2,2.8,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (9,"Bananin napitek","image-8.jpeg","naravni pomarančni sok, banana, med ",2,3.4,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (10,"Limonada","image-9.jpeg","Naravno iztisnjena limonada",2,2.1,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (11,"Coca cola","image-10.jpeg","3dl",3,2.2,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (12,"Fanta","image-11.jpeg","3dl",3,2.2,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (13,"Sprite","image-12.jpeg","3dl",3,2.2,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (14,"Bitter Lemon","image-13.jpeg","3dl",3,2.2,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (15,"Orangina","image-14.jpeg","3dl",3,2.3,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (16,"Tonic","image-15.jpeg","3dl",3,2.2,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (17,"Cockta","image-16.jpeg","3dl",3,2.2,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (18,"Sok v steklenički","image-17.jpeg","jagoda, pomaranča, breskev - 3 dl",3,2.2,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (19,"Radenska","image-18.jpeg","3dl",3,1.6,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (20,"Oaza","image-19.jpeg","5dl",3,1.6,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (21,"Negazirana voda","image-20.jpeg","5dl",3,1.8,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (22,"Ledeni čaj","image-21.jpeg","1dl",3,0.9,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (23,"Red Bull","image-22.jpeg","0,33l",3,3.5,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (24,"Točeno pivo","image-23.jpeg","0,5l",4,2.4,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (25,"Union","image-24.jpeg","0,5l",4,3.1,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (26,"Zlatorog","image-25.jpeg","0,5l",4,2.8,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (27,"Heineken","image-26.jpeg","0,5l",4,3.3,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (28,"Radler","image-27.jpeg","0,5l",4,2.8,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (29,"Brezalkoholno pivo","image-28.jpeg","0,5l",4,3.5,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (30,"Somersby","image-29.jpeg","0,5l",5,3.1,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (31,"Jabolčni TAT","image-30.jpeg","0,33l",5,2.8,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (32,"Jack Daniels","image-31.jpeg","0,03l",6,3.5,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (33,"Johnnie Walker red label","image-32.jpeg","0,03l",6,3.5,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (34,"Jameson","image-33.jpeg","0,33l",6,3.5,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (35,"Domači rum","image-34.jpeg","0,03l",6,3.5,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (36,"Gin Beefeater","image-35.jpeg","0,03l",6,3.5,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (37,"Grappa","image-36.jpeg","0,33l",6,3.5,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (38,"Stock","image-37.jpeg","0,03l",6,3.5,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (39,"Sadjevec","image-38.jpeg","0,03l",6,3.5,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (40,"Travarica","image-39.jpeg","0,33l",6,2.8,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (41,"Belo vino","image-40.jpeg","0,1l",7,1.4,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (42,"Rdeče vino","image-41.jpeg","0,1l",7,1.4,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (43,"Srebrna penina","image-42.jpeg","0,1l",7,1.6,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (44,"Zlata penina","image-43.jpeg","0,1l",7,1.6,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (45,"Prima classica","image-44.jpeg","Pica obložena z šunko, sirom in gobami",8,7.6,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (46,"Prima cremissima","image-45.jpeg","Pica obložena s šunko, sirom in gobovo kremo",8,7.9,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (47,"Prima fresca","image-46.jpeg","Pica obložena s sirom, panceto, rukolo, svežo papriko in šampinjoni",8,8.3,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (48,"Prima giavola","image-47.jpeg","Pica obložena s sirom, salamo, feferoni, papriko in šampinjoni",8,8.6,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (49,"Prima mexicana","image-48.jpeg","Pica obložena z mletim mesom, nacho sirom, rdečim fižolem, papriko in koruzo",8,8.6,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (50,"Con Salame","image-49.jpeg","Pica obložena s sirom, šunko, kuhanim pršutom, suho salamo in gobami",8,8.8,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (51,"Con Prosciutto","image-50.jpeg","Pica obložena s sirom, pršutom in gobami",8,8.6,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (52,"Caprese","image-51.jpeg","Pica obložena z rukolo, sirom, mozzarello in paradižnikom",8,7.6,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (53,"Margherita","image-52.jpeg","Pica obložena s sirom in olivo",8,6.1,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (54,"Con Tonno","image-53.jpeg","Pica obložena s sirom, tuno, tržasko omako in paradižnikom",9,8.2,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (55,"Frutti di mare","image-54.jpeg","Pica obložena s sirom, gamberi, dagnji, lignji in tržasko omako",9,10.6,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (56,"Prima triesta","image-55.jpeg","Pica obložena s sirom, panceto, vratovino, pečeno papriko in tržaško omako",10,8.8,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (57,"Prima speciale","image-56.jpeg","Pica obložena s sirom, umešanim jajčko, mozzarello, budjolo in rukolo",10,10.9,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (58,"Margherita","image-57.jpeg","Napoletana pica obložena s šunko, sirom in gobovo kremo",11,7.6,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (59,"Calabrese","image-58.jpeg","Napoletana pica obložena s šunko, sirom in gobovo kremo",11,11.3,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (60,"Budjola al pistacchio","image-59.jpeg","Napoletana pica obložena s šunko, sirom in gobovo kremo",11,9.8,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (61,"Vegetariano","image-60.jpeg","Napoletana pica obložena s šunko, sirom in gobovo kremo",11,8.8,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (62,"Napoletana","image-61.jpeg","Napoletana pica obložena s šunko, sirom in gobovo kremo",11,9.3,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (63,"Capricciosa","image-62.jpeg","Napoletana pica obložena s šunko, sirom in gobovo kremo",11,9.2,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (64,"Zelenjava","image-63.jpeg","pelati, paradižnik, paprika, melancani, artičoke, beluši, koruza, feferoni, rukola",12,1.2,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (65,"Salame","image-64.jpeg","šunka, kuhan pršut, vratovina, suha salama, hrenovka, pršut, budjola, panceta",12,2.2,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (66,"Siri","image-65.jpeg","trdi sir, mozzarella, beli sir, nacho sir, grana padano",12,2.2,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (67,"Gobe","image-66.jpeg","šampinjoni, jurčki",12,1.4,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (68,"Morski sadeži","image-67.jpeg","mešani morski sadeži, škampi, inčuni",12,2.2,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (69,"Omake in prelivi","image-68.jpeg","jurčkova omaka, tržaška omaka, tatarska omaka, kisla smetana,",12,2.0,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (70,"Jajce","image-69.jpeg","",12,0.8,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (71,"Gratinirane palačinke s skuto","image-70.jpeg","Palačinke s skuto zapečene v krušni peči",13,4.6,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (72,"Palačinke","image-71.jpeg","Palačinke s čokolado, marmelado, lešniki ali orehi",13,4.1,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (73,"Brownie","image-72.jpeg","Topli čokoladni biskvit, sladoled, lešniki",13,5.2,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (74,"Banana split","image-73.jpeg","",13,5.2,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (75,"Sladoled kepica","image-74.jpeg","Izberite si okus pri sladoledni vitrini",13,1.5,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (76,"Svedri z gamberi in pinjolami","image-75.jpeg","Gamberi, pesto, pinjole, češnjev paradižnik, ricotta, paradižnikova omaka, grana padano…",14,11.2,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (77,"Rezanci z morskimi sadeži","image-76.jpeg","gamberi, dagnje, lignji, česen, vino, paradižnikova omaka",14,11.2,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (78,"Tris testenin","image-77.jpeg","Široki rezanci s smetano in pršutom, tortelini s sirom z modro plesnijo, njoki s štirimi zelišči",14,9.4,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (79,"Toskanski tris","image-78.jpeg","Svedri s pomarančo, poprom in piščancem, rižota z jurčki in dimljenim sirom, široki rezanci s smetano in pršutom…",14,9.6,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (80,"Tris klasika","image-79.jpeg","Špageti po bolonjsko, njoki carbonara, mesna lazanja…",14,9.4,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (81,"Lazanja z bolonjsko omako","image-80.jpeg","Testnina, mleto meso s paradižnikovo omako, bešamel, grana padano, kisla smetana, sir…",14,8.1,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (82,"Njoki s 4 siri","image-81.jpeg","Njoki s sirom z modro plesnijo, ementalcem, dimljenim sirom, in grana padanom, zapečni v krušni peči",14,9.6,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (83,"Tortelini s sirom","image-82.jpeg","Tortelini s sirom z modro plesnijo, bučkami, korenjem in smetano, zapčeni v krušni peči",14,10.9,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (84,"Classic burger","image-83.jpeg","Ketchup, majoneza, govedina, zelena solata, čebula, paradižnik",15,7.6,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (85,"Cheeseburger","image-84.jpeg","Ketchup, majoneza, govedina, zelena solata, čebula, paradižnik, sir",15,7.8,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (86,"Chickenburger","image-85.jpeg","Ketchup, majoneza, piščančja prsa, zelena solata, čebula, paradižnik",15,7.5,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (87,"Mexico burger","image-86.jpeg","Koktejl omaka, omaka chili pop, goveje meso, jalapeno paprika, paradižnik, kumare",15,7.9,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (88,"Puranji zrezek po dunajsko","image-87.jpeg","S prilogo: ocvrt krompirčk, tatarska omaka",16,8.6,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (89,"Ocvrt piščančji file","image-88.jpeg","Polnjen s šunko in sirom, priložen pomfrit in tatarska omaka",16,8.9,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (90,"Puranji zrezek s sirom, smetano in gobami","image-89.jpeg","Priloga: krompirjevi kroketi",16,9.1,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (91,"Ocvrti lignji","image-90.jpeg","Priloga: ocvrt krompirčk, tatarska omaka",16,11.2,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (92,"Ocvrt sir","image-91.jpeg","Priloga: ocvrt krompirčk, tatarska omaka",16,7.9,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (93,"Rižota s piščancem in gobami","image-92.jpeg","Piščančji file, gobe, smetana…",17,8.6,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (94,"Paella","image-93.jpeg","Piščančji file, gamberi, paradižnik, smetana, rukola, češnjev paradižnik, grana padano..",17,11.5,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (95,"Rižota z zelenjavo","image-94.jpeg","Paprika, bučke, por, paradižnik, smetana, rukola, češnjev paradižnik, grana padano…",17,6.9,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (96,"Rižota z roastbeefom","image-95.jpeg","Roastbeef, sušeni paradižniki, paradižnikova omaka, rukala, češnjev paradižnik, grana padano…",17,12.2,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (97,"Tunina solata","image-96.jpeg","Zelena solata, radič, rukola, tuna, koromač, koruza, tatarska omaka",18,7.2,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (98,"Mixta","image-97.jpeg","Zelena solata, radič, koruza, rukola, ribani beli sir, olive, hišni preliv…",18,6.9,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (99,"Solata z mozzarello","image-98.jpeg","Zelena solata, radič, koruza, rukola, mozzarella, olive, hišni preliv…",18,6.9,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (100,"Ocvrta solata","image-99.jpeg","Zelena solata, rukola, radič, ocvrte bučke, paprika in melancani, ocvrt sir, tatarska omaka…",18,9.2,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (101,"Piščančja solata","image-100.jpeg","Piščanec v smetanovi omaki, zelena solata, radič, rukola, jajčevci, sojina omaka, balzamični kis…",18,8.1,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (102,"Cezarjeva solata","image-101.jpeg","Zelena solata, radič, piščanec, kruhovke kocke, jajce, rukola, koruza, balzamični preliv…",18,7.9,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (103,"Pomrit","image-102.jpeg","",19,3.5,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (104,"Takitosi","image-103.jpeg","Ocvrti zavitki iz tortilij polnjene s piščancem",19,7.2,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (105,"Zelenjavni takitosi","image-104.jpeg","Ocvrti zavitki iz tortilij polnjene z zelenjavo",19,7.0,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (106,"Hrenovke v listnatem testu","image-105.jpeg","Hrenavke zavite v listanto testo in polite z jajcem",19,5.6,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (107,"Kava","image-106.jpeg","",20,1.3,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (108,"Macchiato","image-107.jpeg","",20,1.6,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (109,"Kava s smetano","image-108.jpeg","",20,1.6,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (110,"Bela kava","image-109.jpeg","",20,1.9,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (111,"Brezkofeinska kava","image-110.jpeg","",20,1.6,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (112,"Irska kava","image-111.jpeg","",21,4.3,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (113,"Ledena kava","image-112.jpeg","",21,3.9,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (114,"Čaj","image-113.jpeg","",22,1.4,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (115,"Vroča čokolada","image-114.jpeg","",22,2.2,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (116,"Kakav","image-115.jpeg","",22,1.7,"EUR");
INSERT INTO item(id, name, image, description, subcategory_id, price, price_unit) VALUES (117,"Mleko","image-116.jpeg","",22,1.0,"EUR");
