INSERT INTO subcategory(id, name, category_id) VALUES (0, Juhe,3);
INSERT INTO subcategory(id, name, category_id) VALUES (1, Hladni napitki,4);
INSERT INTO subcategory(id, name, category_id) VALUES (2, Brezalkoholne pijače,4);
INSERT INTO subcategory(id, name, category_id) VALUES (3, Pivo,4);
INSERT INTO subcategory(id, name, category_id) VALUES (4, Cider,4);
INSERT INTO subcategory(id, name, category_id) VALUES (5, Žgane pijače,4);
INSERT INTO subcategory(id, name, category_id) VALUES (6, Vina,4);
INSERT INTO subcategory(id, name, category_id) VALUES (7, Pice,5);
INSERT INTO subcategory(id, name, category_id) VALUES (8, Morske Pice,5);
INSERT INTO subcategory(id, name, category_id) VALUES (9, Posebne pice,5);
INSERT INTO subcategory(id, name, category_id) VALUES (10, Napoletana,5);
INSERT INTO subcategory(id, name, category_id) VALUES (11, Dodatki,5);
INSERT INTO subcategory(id, name, category_id) VALUES (12, Sladice,6);
INSERT INTO subcategory(id, name, category_id) VALUES (13, Testenine,7);
INSERT INTO subcategory(id, name, category_id) VALUES (14, Burgerji,7);
INSERT INTO subcategory(id, name, category_id) VALUES (15, Navadne jedi,7);
INSERT INTO subcategory(id, name, category_id) VALUES (16, Rižote,7);
INSERT INTO subcategory(id, name, category_id) VALUES (17, Solate,7);
INSERT INTO subcategory(id, name, category_id) VALUES (18, Prigrizki,8);
INSERT INTO subcategory(id, name, category_id) VALUES (19, Kava,9);
INSERT INTO subcategory(id, name, category_id) VALUES (20, Kavni napitki,9);
INSERT INTO subcategory(id, name, category_id) VALUES (21, Topli napitki,9);
